#!/bin/bash

# Define the list of input methods
input_methods=("keyboard-us" "keyboard-us-intl" "mozc", "keyboard-us-dvorak-intl", "keyboard-us-dvorak-classic")

# Get the current input method
current_input=$(fcitx5-remote -n)

# Find the index of the current input method in the list
current_index=-1
for ((i=0; i<${#input_methods[@]}; i++)); do
    if [[ "${input_methods[$i]}" = "${current_input}" ]]; then
        current_index=$i
        break
    fi
done

# Calculate the next index in a cyclic manner
next_index=$(( (current_index + 1) % ${#input_methods[@]} ))

# Get the next input method from the list
next_input="${input_methods[$next_index]}"

# Switch to the next input method
fcitx5-remote -s "$next_input"
