#!/bin/bash

file=$1
filename=$(echo $file | awk -F: '{print $1}')
line=$(echo $file | awk -F: '{print $2}')
if [ ! -f $filename ]; then
    filename="./$filename"
    if [ ! -f $filename ]; then
        tmux display-message -d 4000 "File $filename not found"
        exit 1
    fi
fi
if [ -z "$line" ]; then
    line=1
fi
printf -v location "%s:%s" "$filename" "$line"
tmux new-window "$EDITOR $location"
