[colors.bright]
black = "#3D3839"
red = "#E8838F"
green = "#8BAE68"
yellow = "#D68C67"
blue = "#9C9C9C"
magenta = "#CF86C1"
cyan = "#A0A0A0"
white = "#8E8E8E"

[colors.cursor]
cursor = "#C9C9C9"
text = "#191919"

[colors.normal]
black = "#191919"
blue = "#7A7A7A"
cyan = "#C9C9C9"
green = "#819B69"
magenta = "#B279A7"
red = "#DE6E7C"
white = "#BBBBBB"
yellow = "#B77E64"

[colors.primary]
background = "#202020"
foreground = "#BBBBBB"
