[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Semibold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Semibold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Light Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

