
[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[scrolling]
history = 20000
multiplier = 3

[terminal.shell]
program = "tmux"

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true
import = [
	"~/.config/alacritty/font.toml",
	"~/.config/alacritty/zenwritten.toml"
]

[terminal]
